//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.18 at 10:21:26 AM PDT 
//


package com.genologics.ri.controltype;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.genologics.ri.controltype package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ControlType_QNAME = new QName("http://genologics.com/ri/controltype", "control-type");
    private final static QName _ControlTypes_QNAME = new QName("http://genologics.com/ri/controltype", "control-types");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.genologics.ri.controltype
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ControlType }
     * 
     */
    public ControlType createControlType() {
        return new ControlType();
    }

    /**
     * Create an instance of {@link ControlTypes }
     * 
     */
    public ControlTypes createControlTypes() {
        return new ControlTypes();
    }

    /**
     * Create an instance of {@link ControlTypeLink }
     * 
     */
    public ControlTypeLink createControlTypeLink() {
        return new ControlTypeLink();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ControlType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://genologics.com/ri/controltype", name = "control-type")
    public JAXBElement<ControlType> createControlType(ControlType value) {
        return new JAXBElement<ControlType>(_ControlType_QNAME, ControlType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ControlTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://genologics.com/ri/controltype", name = "control-types")
    public JAXBElement<ControlTypes> createControlTypes(ControlTypes value) {
        return new JAXBElement<ControlTypes>(_ControlTypes_QNAME, ControlTypes.class, null, value);
    }

}
