//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.18 at 10:21:26 AM PDT 
//


package com.genologics.ri.stepconfiguration;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for trigger-status.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="trigger-status">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="STARTED"/>
 *     &lt;enumeration value="STEP_SETUP"/>
 *     &lt;enumeration value="POOLING"/>
 *     &lt;enumeration value="PLACEMENT"/>
 *     &lt;enumeration value="ADD_REAGENT"/>
 *     &lt;enumeration value="RECORD_DETAILS"/>
 *     &lt;enumeration value="COMPLETE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "trigger-status")
@XmlEnum
public enum TriggerStatus {

    STARTED,
    STEP_SETUP,
    POOLING,
    PLACEMENT,
    ADD_REAGENT,
    RECORD_DETAILS,
    COMPLETE;

    public String value() {
        return name();
    }

    public static TriggerStatus fromValue(String v) {
        return valueOf(v);
    }

}
