//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.18 at 10:21:26 AM PDT 
//


package com.genologics.ri.step;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for action-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="action-type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="leave"/>
 *     &lt;enumeration value="repeat"/>
 *     &lt;enumeration value="remove"/>
 *     &lt;enumeration value="review"/>
 *     &lt;enumeration value="complete"/>
 *     &lt;enumeration value="store"/>
 *     &lt;enumeration value="nextstep"/>
 *     &lt;enumeration value="rework"/>
 *     &lt;enumeration value="unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "action-type")
@XmlEnum
public enum ActionType {

    @XmlEnumValue("leave")
    LEAVE("leave"),
    @XmlEnumValue("repeat")
    REPEAT("repeat"),
    @XmlEnumValue("remove")
    REMOVE("remove"),
    @XmlEnumValue("review")
    REVIEW("review"),
    @XmlEnumValue("complete")
    COMPLETE("complete"),
    @XmlEnumValue("store")
    STORE("store"),
    @XmlEnumValue("nextstep")
    NEXTSTEP("nextstep"),
    @XmlEnumValue("rework")
    REWORK("rework"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown");
    private final String value;

    ActionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActionType fromValue(String v) {
        for (ActionType c: ActionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
