//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.18 at 10:21:26 AM PDT 
//


package com.genologics.ri.step;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.genologics.ri.step package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Step_QNAME = new QName("http://genologics.com/ri/step", "step");
    private final static QName _Actions_QNAME = new QName("http://genologics.com/ri/step", "actions");
    private final static QName _Reagents_QNAME = new QName("http://genologics.com/ri/step", "reagents");
    private final static QName _Placements_QNAME = new QName("http://genologics.com/ri/step", "placements");
    private final static QName _Pools_QNAME = new QName("http://genologics.com/ri/step", "pools");
    private final static QName _ProgramStatus_QNAME = new QName("http://genologics.com/ri/step", "program-status");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.genologics.ri.step
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Actions }
     * 
     */
    public Actions createActions() {
        return new Actions();
    }

    /**
     * Create an instance of {@link Pools }
     * 
     */
    public Pools createPools() {
        return new Pools();
    }

    /**
     * Create an instance of {@link Placements }
     * 
     */
    public Placements createPlacements() {
        return new Placements();
    }

    /**
     * Create an instance of {@link Reagents }
     * 
     */
    public Reagents createReagents() {
        return new Reagents();
    }

    /**
     * Create an instance of {@link ProgramStatus }
     * 
     */
    public ProgramStatus createProgramStatus() {
        return new ProgramStatus();
    }

    /**
     * Create an instance of {@link Step }
     * 
     */
    public Step createStep() {
        return new Step();
    }

    /**
     * Create an instance of {@link ReagentLabel }
     * 
     */
    public ReagentLabel createReagentLabel() {
        return new ReagentLabel();
    }

    /**
     * Create an instance of {@link StepConfiguration }
     * 
     */
    public StepConfiguration createStepConfiguration() {
        return new StepConfiguration();
    }

    /**
     * Create an instance of {@link ReagentsLink }
     * 
     */
    public ReagentsLink createReagentsLink() {
        return new ReagentsLink();
    }

    /**
     * Create an instance of {@link OutputPlacement }
     * 
     */
    public OutputPlacement createOutputPlacement() {
        return new OutputPlacement();
    }

    /**
     * Create an instance of {@link com.genologics.ri.step.PooledInputs }
     * 
     */
    public com.genologics.ri.step.PooledInputs createPooledInputs() {
        return new com.genologics.ri.step.PooledInputs();
    }

    /**
     * Create an instance of {@link ProgramStatusLink }
     * 
     */
    public ProgramStatusLink createProgramStatusLink() {
        return new ProgramStatusLink();
    }

    /**
     * Create an instance of {@link PlacementsLink }
     * 
     */
    public PlacementsLink createPlacementsLink() {
        return new PlacementsLink();
    }

    /**
     * Create an instance of {@link Input }
     * 
     */
    public Input createInput() {
        return new Input();
    }

    /**
     * Create an instance of {@link Container }
     * 
     */
    public Container createContainer() {
        return new Container();
    }

    /**
     * Create an instance of {@link ActionsLink }
     * 
     */
    public ActionsLink createActionsLink() {
        return new ActionsLink();
    }

    /**
     * Create an instance of {@link NextAction }
     * 
     */
    public NextAction createNextAction() {
        return new NextAction();
    }

    /**
     * Create an instance of {@link Output }
     * 
     */
    public Output createOutput() {
        return new Output();
    }

    /**
     * Create an instance of {@link PoolsLink }
     * 
     */
    public PoolsLink createPoolsLink() {
        return new PoolsLink();
    }

    /**
     * Create an instance of {@link Actions.NextActions }
     * 
     */
    public Actions.NextActions createActionsNextActions() {
        return new Actions.NextActions();
    }

    /**
     * Create an instance of {@link Pools.PooledInputs }
     * 
     */
    public Pools.PooledInputs createPoolsPooledInputs() {
        return new Pools.PooledInputs();
    }

    /**
     * Create an instance of {@link Pools.AvailableInputs }
     * 
     */
    public Pools.AvailableInputs createPoolsAvailableInputs() {
        return new Pools.AvailableInputs();
    }

    /**
     * Create an instance of {@link Placements.SelectedContainers }
     * 
     */
    public Placements.SelectedContainers createPlacementsSelectedContainers() {
        return new Placements.SelectedContainers();
    }

    /**
     * Create an instance of {@link Placements.OutputPlacements }
     * 
     */
    public Placements.OutputPlacements createPlacementsOutputPlacements() {
        return new Placements.OutputPlacements();
    }

    /**
     * Create an instance of {@link Reagents.OutputReagents }
     * 
     */
    public Reagents.OutputReagents createReagentsOutputReagents() {
        return new Reagents.OutputReagents();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Step }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://genologics.com/ri/step", name = "step")
    public JAXBElement<Step> createStep(Step value) {
        return new JAXBElement<Step>(_Step_QNAME, Step.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Actions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://genologics.com/ri/step", name = "actions")
    public JAXBElement<Actions> createActions(Actions value) {
        return new JAXBElement<Actions>(_Actions_QNAME, Actions.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Reagents }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://genologics.com/ri/step", name = "reagents")
    public JAXBElement<Reagents> createReagents(Reagents value) {
        return new JAXBElement<Reagents>(_Reagents_QNAME, Reagents.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Placements }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://genologics.com/ri/step", name = "placements")
    public JAXBElement<Placements> createPlacements(Placements value) {
        return new JAXBElement<Placements>(_Placements_QNAME, Placements.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Pools }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://genologics.com/ri/step", name = "pools")
    public JAXBElement<Pools> createPools(Pools value) {
        return new JAXBElement<Pools>(_Pools_QNAME, Pools.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProgramStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://genologics.com/ri/step", name = "program-status")
    public JAXBElement<ProgramStatus> createProgramStatus(ProgramStatus value) {
        return new JAXBElement<ProgramStatus>(_ProgramStatus_QNAME, ProgramStatus.class, null, value);
    }

}
