//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.18 at 10:21:26 AM PDT 
//


package com.genologics.ri.step;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.genologics.ri.Link;


/**
 * 
 *         The detailed representation of a step's output artifact reagents.
 *       
 * 
 * <p>Java class for reagents complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reagents">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="step" type="{http://genologics.com/ri}link" minOccurs="0"/>
 *         &lt;element name="configuration" type="{http://genologics.com/ri/step}step-configuration" minOccurs="0"/>
 *         &lt;element name="reagent-category" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="output-reagents" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="output" type="{http://genologics.com/ri/step}output" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reagents", propOrder = {
    "step",
    "configuration",
    "reagentCategory",
    "outputReagents"
})
public class Reagents {

    protected Link step;
    protected StepConfiguration configuration;
    @XmlElement(name = "reagent-category")
    protected String reagentCategory;
    @XmlElement(name = "output-reagents")
    protected Reagents.OutputReagents outputReagents;
    @XmlAttribute(name = "uri")
    @XmlSchemaType(name = "anyURI")
    protected String uri;

    /**
     * Gets the value of the step property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getStep() {
        return step;
    }

    /**
     * Sets the value of the step property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setStep(Link value) {
        this.step = value;
    }

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     {@link StepConfiguration }
     *     
     */
    public StepConfiguration getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link StepConfiguration }
     *     
     */
    public void setConfiguration(StepConfiguration value) {
        this.configuration = value;
    }

    /**
     * Gets the value of the reagentCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReagentCategory() {
        return reagentCategory;
    }

    /**
     * Sets the value of the reagentCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReagentCategory(String value) {
        this.reagentCategory = value;
    }

    /**
     * Gets the value of the outputReagents property.
     * 
     * @return
     *     possible object is
     *     {@link Reagents.OutputReagents }
     *     
     */
    public Reagents.OutputReagents getOutputReagents() {
        return outputReagents;
    }

    /**
     * Sets the value of the outputReagents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reagents.OutputReagents }
     *     
     */
    public void setOutputReagents(Reagents.OutputReagents value) {
        this.outputReagents = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="output" type="{http://genologics.com/ri/step}output" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "output"
    })
    public static class OutputReagents {

        protected List<Output> output;

        /**
         * Gets the value of the output property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the output property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOutput().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Output }
         * 
         * 
         */
        public List<Output> getOutput() {
            if (output == null) {
                output = new ArrayList<Output>();
            }
            return this.output;
        }

    }

}
