//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.18 at 10:21:26 AM PDT 
//


package com.genologics.ri.process;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Artifact is a child element of input-output-map and provides a link to an Artifact that was either
 * an input or output of the Process for the input-output-map.
 *       
 * 
 * <p>Java class for artifact complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="artifact">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parent-process" type="{http://genologics.com/ri/process}parent-process" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="limsid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="output-type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="output-generation-type" type="{http://genologics.com/ri/process}output-generation-type" />
 *       &lt;attribute name="uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="post-process-uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "artifact", propOrder = {
    "parentProcess"
})
public class Artifact {

    @XmlElement(name = "parent-process")
    protected ParentProcess parentProcess;
    @XmlAttribute(name = "limsid")
    protected String limsid;
    @XmlAttribute(name = "output-type")
    protected String outputType;
    @XmlAttribute(name = "output-generation-type")
    protected OutputGenerationType outputGenerationType;
    @XmlAttribute(name = "uri")
    @XmlSchemaType(name = "anyURI")
    protected String uri;
    @XmlAttribute(name = "post-process-uri")
    @XmlSchemaType(name = "anyURI")
    protected String postProcessUri;

    /**
     * Gets the value of the parentProcess property.
     * 
     * @return
     *     possible object is
     *     {@link ParentProcess }
     *     
     */
    public ParentProcess getParentProcess() {
        return parentProcess;
    }

    /**
     * Sets the value of the parentProcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentProcess }
     *     
     */
    public void setParentProcess(ParentProcess value) {
        this.parentProcess = value;
    }

    /**
     * Gets the value of the limsid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLimsid() {
        return limsid;
    }

    /**
     * Sets the value of the limsid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLimsid(String value) {
        this.limsid = value;
    }

    /**
     * Gets the value of the outputType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputType() {
        return outputType;
    }

    /**
     * Sets the value of the outputType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputType(String value) {
        this.outputType = value;
    }

    /**
     * Gets the value of the outputGenerationType property.
     * 
     * @return
     *     possible object is
     *     {@link OutputGenerationType }
     *     
     */
    public OutputGenerationType getOutputGenerationType() {
        return outputGenerationType;
    }

    /**
     * Sets the value of the outputGenerationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputGenerationType }
     *     
     */
    public void setOutputGenerationType(OutputGenerationType value) {
        this.outputGenerationType = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

    /**
     * Gets the value of the postProcessUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostProcessUri() {
        return postProcessUri;
    }

    /**
     * Sets the value of the postProcessUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostProcessUri(String value) {
        this.postProcessUri = value;
    }

}
