/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniExample1 */

#ifndef _Included_JniExample1
#define _Included_JniExample1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniExample1
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JniExample1_intMethod
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
