//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.18 at 10:21:26 AM PDT 
//


package com.genologics.ri.artifact;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.genologics.ri.Location;
import com.genologics.ri.file.File;
import com.genologics.ri.userdefined.Field;


/**
 * 
 *         <p>The detailed representation of an Artifact.</p>
 * <p>An Artifact represents the inputs to or outputs from a process. An Artifact is
 * classified by its type (Analyte, ResultFile, etc).</p>
 * <p>Artifacts do not support HTTP POST requests.</p>
 *       
 * 
 * <p>Java class for artifact complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="artifact">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="output-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="parent-process" type="{http://genologics.com/ri/artifact}parent-process" minOccurs="0"/>
 *         &lt;element name="qc-flag" type="{http://genologics.com/ri/artifact}qc-flag" minOccurs="0"/>
 *         &lt;element name="location" type="{http://genologics.com/ri}location" minOccurs="0"/>
 *         &lt;element name="working-flag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="sample" type="{http://genologics.com/ri/artifact}sample" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reagent-label" type="{http://genologics.com/ri/artifact}reagent-label" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="control-type" type="{http://genologics.com/ri/artifact}control-type" minOccurs="0"/>
 *         &lt;element ref="{http://genologics.com/ri/userdefined}field" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://genologics.com/ri/file}file" minOccurs="0"/>
 *         &lt;element name="artifact-group" type="{http://genologics.com/ri/artifact}artifactgroup" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="limsid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "artifact", propOrder = {
    "name",
    "type",
    "outputType",
    "parentProcess",
    "qcFlag",
    "location",
    "workingFlag",
    "sample",
    "reagentLabel",
    "controlType",
    "field",
    "file",
    "artifactGroup"
})
public class Artifact {

    protected String name;
    protected String type;
    @XmlElement(name = "output-type")
    protected String outputType;
    @XmlElement(name = "parent-process")
    protected ParentProcess parentProcess;
    @XmlElement(name = "qc-flag")
    protected QcFlag qcFlag;
    protected Location location;
    @XmlElement(name = "working-flag")
    protected Boolean workingFlag;
    protected List<Sample> sample;
    @XmlElement(name = "reagent-label")
    protected List<ReagentLabel> reagentLabel;
    @XmlElement(name = "control-type")
    protected ControlType controlType;
    @XmlElement(namespace = "http://genologics.com/ri/userdefined")
    protected List<Field> field;
    @XmlElement(namespace = "http://genologics.com/ri/file")
    protected File file;
    @XmlElement(name = "artifact-group")
    protected List<Artifactgroup> artifactGroup;
    @XmlAttribute(name = "limsid")
    protected String limsid;
    @XmlAttribute(name = "uri")
    @XmlSchemaType(name = "anyURI")
    protected String uri;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the outputType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputType() {
        return outputType;
    }

    /**
     * Sets the value of the outputType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputType(String value) {
        this.outputType = value;
    }

    /**
     * Gets the value of the parentProcess property.
     * 
     * @return
     *     possible object is
     *     {@link ParentProcess }
     *     
     */
    public ParentProcess getParentProcess() {
        return parentProcess;
    }

    /**
     * Sets the value of the parentProcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentProcess }
     *     
     */
    public void setParentProcess(ParentProcess value) {
        this.parentProcess = value;
    }

    /**
     * Gets the value of the qcFlag property.
     * 
     * @return
     *     possible object is
     *     {@link QcFlag }
     *     
     */
    public QcFlag getQcFlag() {
        return qcFlag;
    }

    /**
     * Sets the value of the qcFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link QcFlag }
     *     
     */
    public void setQcFlag(QcFlag value) {
        this.qcFlag = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setLocation(Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the workingFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWorkingFlag() {
        return workingFlag;
    }

    /**
     * Sets the value of the workingFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWorkingFlag(Boolean value) {
        this.workingFlag = value;
    }

    /**
     * Gets the value of the sample property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sample property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSample().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sample }
     * 
     * 
     */
    public List<Sample> getSample() {
        if (sample == null) {
            sample = new ArrayList<Sample>();
        }
        return this.sample;
    }

    /**
     * Gets the value of the reagentLabel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reagentLabel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReagentLabel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReagentLabel }
     * 
     * 
     */
    public List<ReagentLabel> getReagentLabel() {
        if (reagentLabel == null) {
            reagentLabel = new ArrayList<ReagentLabel>();
        }
        return this.reagentLabel;
    }

    /**
     * Gets the value of the controlType property.
     * 
     * @return
     *     possible object is
     *     {@link ControlType }
     *     
     */
    public ControlType getControlType() {
        return controlType;
    }

    /**
     * Sets the value of the controlType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlType }
     *     
     */
    public void setControlType(ControlType value) {
        this.controlType = value;
    }

    /**
     * 
     *             A User-Defined Field that is associated with the Artifact.
     * This element is repeated for each UDF associated with the Artifact.
     * <br/>Always returns with GET: No
     * <br/>Updatable with PUT: Yes
     * <br/>Required for PUT: No, unless the UDF has been configured as required. If a current UDF is not provided, existing values are deleted.
     *           Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * 
     * 
     */
    public List<Field> getField() {
        if (field == null) {
            field = new ArrayList<Field>();
        }
        return this.field;
    }

    /**
     * 
     *             File provides a URI linking to the detailed representation of the File associated with the Artifact.
     * <br/>Always returns with GET: No
     * <br/>Updatable with PUT: Yes, only supported for SearchResultFile, ResultFile, and SpotList type Artifacts.
     * <br/>Required for PUT: No
     *           
     * 
     * @return
     *     possible object is
     *     {@link File }
     *     
     */
    public File getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link File }
     *     
     */
    public void setFile(File value) {
        this.file = value;
    }

    /**
     * Gets the value of the artifactGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the artifactGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArtifactGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Artifactgroup }
     * 
     * 
     */
    public List<Artifactgroup> getArtifactGroup() {
        if (artifactGroup == null) {
            artifactGroup = new ArrayList<Artifactgroup>();
        }
        return this.artifactGroup;
    }

    /**
     * Gets the value of the limsid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLimsid() {
        return limsid;
    }

    /**
     * Sets the value of the limsid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLimsid(String value) {
        this.limsid = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

}
