//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.18 at 10:21:26 AM PDT 
//


package com.genologics.ri.containertype;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The detailed representation of a container type.
 * <p>The container type describes the physical characteristics of a class of containers such as
 * the number of wells in the container as well as describing the coordinate system used for identifying
 * those wells.</p>
 * <p>The container type is described using a rectangular coordinate system. The
 * characteristics of the horizontal axis are described by the x-dimension element, and the characteristics
 * of the vertical dimension are described by the y-dimension child elements. The characteristics of
 * each dimension included both the size in that dimension as well as the identification method for
 * values in that dimension. Values can be identified either numerically where 0 is the first item or
 * alphabetically where A is the first element. Additionally an offset can be specified which shifts the
 * value of the first element by a fixed amount. When a well location is represented using the coordinate
 * system, it is shown as Y-Value:X-Value (for example A:1).<p>
 * <p>The following are examples of the coordinate system:<p>
 * <ul>
 * <li>Y-Dimension: alphabetic, size 1, offset 0. X-Dimension: numeric, size 1, offset 0. Size: 1. Valid value: A:0</li>
 * <li>Y-Dimension: alphabetic, size 12, offset 0. X-Dimension: numeric, size 8, offset 0. Size: 96. Valid values: A:0 ... L:7</li>
 * <li>Y-Dimension: alphabetic, size 8, offset 0. X-Dimension: numeric, size 12, offset 1. Size: 96. Valid values: A:1 ... H:12</li>
 * </ul>
 * <p>The container type also identifies wells in the container that are not available for storing
 * samples or reagents, either because the configuration of the container requires those wells to
 * be empty for the instrument configuration or because the well contains specific calibrants that
 * are required by the instrument. The well location of the calibrant or unavailable wells is specified
 * using the coordinate system that is described by the x-dimension and y-dimension of the container
 * type.</p>
 *       
 * 
 * <p>Java class for container-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="container-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="is-tube" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="calibrant-well" type="{http://genologics.com/ri/containertype}calibrant-well" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="unavailable-well" type="{http://genologics.com/ri/containertype}unavailable-well" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="x-dimension" type="{http://genologics.com/ri/containertype}dimension" minOccurs="0"/>
 *         &lt;element name="y-dimension" type="{http://genologics.com/ri/containertype}dimension" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "container-type", propOrder = {
    "isTube",
    "calibrantWell",
    "unavailableWell",
    "xDimension",
    "yDimension"
})
public class ContainerType {

    @XmlElement(name = "is-tube")
    protected Boolean isTube;
    @XmlElement(name = "calibrant-well")
    protected List<CalibrantWell> calibrantWell;
    @XmlElement(name = "unavailable-well")
    protected List<String> unavailableWell;
    @XmlElement(name = "x-dimension")
    protected Dimension xDimension;
    @XmlElement(name = "y-dimension")
    protected Dimension yDimension;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "uri")
    @XmlSchemaType(name = "anyURI")
    protected String uri;

    /**
     * Gets the value of the isTube property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsTube() {
        return isTube;
    }

    /**
     * Sets the value of the isTube property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsTube(Boolean value) {
        this.isTube = value;
    }

    /**
     * Gets the value of the calibrantWell property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the calibrantWell property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCalibrantWell().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CalibrantWell }
     * 
     * 
     */
    public List<CalibrantWell> getCalibrantWell() {
        if (calibrantWell == null) {
            calibrantWell = new ArrayList<CalibrantWell>();
        }
        return this.calibrantWell;
    }

    /**
     * Gets the value of the unavailableWell property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unavailableWell property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnavailableWell().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUnavailableWell() {
        if (unavailableWell == null) {
            unavailableWell = new ArrayList<String>();
        }
        return this.unavailableWell;
    }

    /**
     * Gets the value of the xDimension property.
     * 
     * @return
     *     possible object is
     *     {@link Dimension }
     *     
     */
    public Dimension getXDimension() {
        return xDimension;
    }

    /**
     * Sets the value of the xDimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dimension }
     *     
     */
    public void setXDimension(Dimension value) {
        this.xDimension = value;
    }

    /**
     * Gets the value of the yDimension property.
     * 
     * @return
     *     possible object is
     *     {@link Dimension }
     *     
     */
    public Dimension getYDimension() {
        return yDimension;
    }

    /**
     * Sets the value of the yDimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dimension }
     *     
     */
    public void setYDimension(Dimension value) {
        this.yDimension = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

}
