//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.18 at 10:21:26 AM PDT 
//


package com.genologics.ri.containertype;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.genologics.ri.containertype package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ContainerType_QNAME = new QName("http://genologics.com/ri/containertype", "container-type");
    private final static QName _ContainerTypes_QNAME = new QName("http://genologics.com/ri/containertype", "container-types");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.genologics.ri.containertype
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ContainerTypes }
     * 
     */
    public ContainerTypes createContainerTypes() {
        return new ContainerTypes();
    }

    /**
     * Create an instance of {@link ContainerType }
     * 
     */
    public ContainerType createContainerType() {
        return new ContainerType();
    }

    /**
     * Create an instance of {@link Dimension }
     * 
     */
    public Dimension createDimension() {
        return new Dimension();
    }

    /**
     * Create an instance of {@link ContainerTypeLink }
     * 
     */
    public ContainerTypeLink createContainerTypeLink() {
        return new ContainerTypeLink();
    }

    /**
     * Create an instance of {@link CalibrantWell }
     * 
     */
    public CalibrantWell createCalibrantWell() {
        return new CalibrantWell();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContainerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://genologics.com/ri/containertype", name = "container-type")
    public JAXBElement<ContainerType> createContainerType(ContainerType value) {
        return new JAXBElement<ContainerType>(_ContainerType_QNAME, ContainerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContainerTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://genologics.com/ri/containertype", name = "container-types")
    public JAXBElement<ContainerTypes> createContainerTypes(ContainerTypes value) {
        return new JAXBElement<ContainerTypes>(_ContainerTypes_QNAME, ContainerTypes.class, null, value);
    }

}
