//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.18 at 10:21:26 AM PDT 
//


package com.genologics.ri.sample;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.genologics.ri.sample package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Samples_QNAME = new QName("http://genologics.com/ri/sample", "samples");
    private final static QName _Sample_QNAME = new QName("http://genologics.com/ri/sample", "sample");
    private final static QName _Samplecreation_QNAME = new QName("http://genologics.com/ri/sample", "samplecreation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.genologics.ri.sample
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Samplecreation }
     * 
     */
    public Samplecreation createSamplecreation() {
        return new Samplecreation();
    }

    /**
     * Create an instance of {@link Samples }
     * 
     */
    public Samples createSamples() {
        return new Samples();
    }

    /**
     * Create an instance of {@link Sample }
     * 
     */
    public Sample createSample() {
        return new Sample();
    }

    /**
     * Create an instance of {@link SampleLink }
     * 
     */
    public SampleLink createSampleLink() {
        return new SampleLink();
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link Artifact }
     * 
     */
    public Artifact createArtifact() {
        return new Artifact();
    }

    /**
     * Create an instance of {@link Biosource }
     * 
     */
    public Biosource createBiosource() {
        return new Biosource();
    }

    /**
     * Create an instance of {@link Samplebase }
     * 
     */
    public Samplebase createSamplebase() {
        return new Samplebase();
    }

    /**
     * Create an instance of {@link Submitter }
     * 
     */
    public Submitter createSubmitter() {
        return new Submitter();
    }

    /**
     * Create an instance of {@link ControlType }
     * 
     */
    public ControlType createControlType() {
        return new ControlType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Samples }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://genologics.com/ri/sample", name = "samples")
    public JAXBElement<Samples> createSamples(Samples value) {
        return new JAXBElement<Samples>(_Samples_QNAME, Samples.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sample }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://genologics.com/ri/sample", name = "sample")
    public JAXBElement<Sample> createSample(Sample value) {
        return new JAXBElement<Sample>(_Sample_QNAME, Sample.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Samplecreation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://genologics.com/ri/sample", name = "samplecreation")
    public JAXBElement<Samplecreation> createSamplecreation(Samplecreation value) {
        return new JAXBElement<Samplecreation>(_Samplecreation_QNAME, Samplecreation.class, null, value);
    }

}
