//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.18 at 10:21:26 AM PDT 
//


package com.genologics.ri.routing;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.genologics.ri.routing package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Routing_QNAME = new QName("http://genologics.com/ri/routing", "routing");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.genologics.ri.routing
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Routing }
     * 
     */
    public Routing createRouting() {
        return new Routing();
    }

    /**
     * Create an instance of {@link Artifact }
     * 
     */
    public Artifact createArtifact() {
        return new Artifact();
    }

    /**
     * Create an instance of {@link ExtArtifactAssignments }
     * 
     */
    public ExtArtifactAssignments createExtArtifactAssignments() {
        return new ExtArtifactAssignments();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Routing }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://genologics.com/ri/routing", name = "routing")
    public JAXBElement<Routing> createRouting(Routing value) {
        return new JAXBElement<Routing>(_Routing_QNAME, Routing.class, null, value);
    }

}
