//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.18 at 10:21:26 AM PDT 
//


package com.genologics.ri.lab;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.genologics.ri.lab package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Labs_QNAME = new QName("http://genologics.com/ri/lab", "labs");
    private final static QName _Lab_QNAME = new QName("http://genologics.com/ri/lab", "lab");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.genologics.ri.lab
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Labs }
     * 
     */
    public Labs createLabs() {
        return new Labs();
    }

    /**
     * Create an instance of {@link Lab }
     * 
     */
    public Lab createLab() {
        return new Lab();
    }

    /**
     * Create an instance of {@link LabLink }
     * 
     */
    public LabLink createLabLink() {
        return new LabLink();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Labs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://genologics.com/ri/lab", name = "labs")
    public JAXBElement<Labs> createLabs(Labs value) {
        return new JAXBElement<Labs>(_Labs_QNAME, Labs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Lab }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://genologics.com/ri/lab", name = "lab")
    public JAXBElement<Lab> createLab(Lab value) {
        return new JAXBElement<Lab>(_Lab_QNAME, Lab.class, null, value);
    }

}
