//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.18 at 10:21:26 AM PDT 
//


package com.genologics.ri.protocolconfiguration;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.genologics.ri.protocolconfiguration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Protocol_QNAME = new QName("http://genologics.com/ri/protocolconfiguration", "protocol");
    private final static QName _Protocols_QNAME = new QName("http://genologics.com/ri/protocolconfiguration", "protocols");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.genologics.ri.protocolconfiguration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Protocol }
     * 
     */
    public Protocol createProtocol() {
        return new Protocol();
    }

    /**
     * Create an instance of {@link Protocols }
     * 
     */
    public Protocols createProtocols() {
        return new Protocols();
    }

    /**
     * Create an instance of {@link ProtocolLink }
     * 
     */
    public ProtocolLink createProtocolLink() {
        return new ProtocolLink();
    }

    /**
     * Create an instance of {@link ProtocolProperty }
     * 
     */
    public ProtocolProperty createProtocolProperty() {
        return new ProtocolProperty();
    }

    /**
     * Create an instance of {@link Protocol.Steps }
     * 
     */
    public Protocol.Steps createProtocolSteps() {
        return new Protocol.Steps();
    }

    /**
     * Create an instance of {@link Protocol.ProtocolProperties }
     * 
     */
    public Protocol.ProtocolProperties createProtocolProtocolProperties() {
        return new Protocol.ProtocolProperties();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Protocol }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://genologics.com/ri/protocolconfiguration", name = "protocol")
    public JAXBElement<Protocol> createProtocol(Protocol value) {
        return new JAXBElement<Protocol>(_Protocol_QNAME, Protocol.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Protocols }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://genologics.com/ri/protocolconfiguration", name = "protocols")
    public JAXBElement<Protocols> createProtocols(Protocols value) {
        return new JAXBElement<Protocols>(_Protocols_QNAME, Protocols.class, null, value);
    }

}
