//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.18 at 10:21:26 AM PDT 
//


package com.genologics.ri.processtype;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.genologics.ri.configuration.FieldLink;


/**
 * 
 *         Process-output is a child element of process type specifying the configured output generation types for the process
 *       
 * 
 * <p>Java class for process-output complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="process-output">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="artifact-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="display-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="output-generation-type" type="{http://genologics.com/ri/processtype}output-generation-type" minOccurs="0"/>
 *         &lt;element name="variability-type" type="{http://genologics.com/ri/processtype}variability-type" minOccurs="0"/>
 *         &lt;element name="number-of-outputs" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="output-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="field-definition" type="{http://genologics.com/ri/configuration}field-link" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="assign-working-flag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "process-output", propOrder = {
    "artifactType",
    "displayName",
    "outputGenerationType",
    "variabilityType",
    "numberOfOutputs",
    "outputName",
    "fieldDefinition",
    "assignWorkingFlag"
})
public class ProcessOutput {

    @XmlElement(name = "artifact-type")
    protected String artifactType;
    @XmlElement(name = "display-name")
    protected String displayName;
    @XmlElement(name = "output-generation-type")
    protected OutputGenerationType outputGenerationType;
    @XmlElement(name = "variability-type")
    protected VariabilityType variabilityType;
    @XmlElement(name = "number-of-outputs")
    protected Integer numberOfOutputs;
    @XmlElement(name = "output-name")
    protected String outputName;
    @XmlElement(name = "field-definition")
    protected List<FieldLink> fieldDefinition;
    @XmlElement(name = "assign-working-flag")
    protected Boolean assignWorkingFlag;

    /**
     * Gets the value of the artifactType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtifactType() {
        return artifactType;
    }

    /**
     * Sets the value of the artifactType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtifactType(String value) {
        this.artifactType = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the outputGenerationType property.
     * 
     * @return
     *     possible object is
     *     {@link OutputGenerationType }
     *     
     */
    public OutputGenerationType getOutputGenerationType() {
        return outputGenerationType;
    }

    /**
     * Sets the value of the outputGenerationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputGenerationType }
     *     
     */
    public void setOutputGenerationType(OutputGenerationType value) {
        this.outputGenerationType = value;
    }

    /**
     * Gets the value of the variabilityType property.
     * 
     * @return
     *     possible object is
     *     {@link VariabilityType }
     *     
     */
    public VariabilityType getVariabilityType() {
        return variabilityType;
    }

    /**
     * Sets the value of the variabilityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariabilityType }
     *     
     */
    public void setVariabilityType(VariabilityType value) {
        this.variabilityType = value;
    }

    /**
     * Gets the value of the numberOfOutputs property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfOutputs() {
        return numberOfOutputs;
    }

    /**
     * Sets the value of the numberOfOutputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfOutputs(Integer value) {
        this.numberOfOutputs = value;
    }

    /**
     * Gets the value of the outputName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputName() {
        return outputName;
    }

    /**
     * Sets the value of the outputName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputName(String value) {
        this.outputName = value;
    }

    /**
     * Gets the value of the fieldDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FieldLink }
     * 
     * 
     */
    public List<FieldLink> getFieldDefinition() {
        if (fieldDefinition == null) {
            fieldDefinition = new ArrayList<FieldLink>();
        }
        return this.fieldDefinition;
    }

    /**
     * Gets the value of the assignWorkingFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAssignWorkingFlag() {
        return assignWorkingFlag;
    }

    /**
     * Sets the value of the assignWorkingFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAssignWorkingFlag(Boolean value) {
        this.assignWorkingFlag = value;
    }

}
